### PR TITLE
[WIP] Adding PySAL Code of Conduct to pysal.org

### PR DESCRIPTION
**Pull request by jGaboardi**
Addressing pysal/pysal.site#26

***This is not a complete CoC, still needs work***; see [checklist of to dos](https://github.com/pysal/pysal.site/issues/26#issuecomment-446967532)

NEED HELP: @weikang9009 @sjsrey 

- [ ] Getting a "Code of Conduct" link in the upper index

- [ ] ~~Setting up `pysal_CoC google_group`? ([follow discussion here](https://github.com/pysal/pysal/issues/1067#issuecomment-451757748))~~

- [x] Setting up `pysal/code_of_conduct` gitter channel without having an actual repo associated with it

- ~[ ] set up `@pysal.org` email ([see 7. here for name ideas](https://hackmd.io/-YBZEY4PRSG6-2Fq6JHNuQ?both))~

### CODE REVIEW

**Comment by jGaboardi** [comment]
Migrating from pysal/pysal#1062

**Comment by weikang9009** [comment]
Could you push your local changes in the source repo `pysal.site` to your [remote](https://github.com/jGaboardi/pysal.site)? I could pull your changes to my local and make some adjustments.

**Comment by jGaboardi** [comment]
@weikang9009 I just pushed the changes I made up to [`jGaboardi/pysal.site`](https://github.com/jGaboardi/pysal.site)

**Comment by jGaboardi** [comment]
> It might make more sense to merge "CODE_OF_CONDUCT" and "CoC_reporting" into one file so that we will have one webpage for code of conduct?

Would you like me to merge these two files? Or did you want to do you?

**Comment by weikang9009** [comment]
Thank you @jGaboardi ! I will merge them, open a PR in [pysal/pysal.site](https://github.com/pysal/pysal.site) and request your review.

**Comment by jGaboardi** [comment]
pysal/pysal#1067

**Comment by slumnitz** [comment]
Maybe we can add a "developers guide" to the navigation bar, which will include CoC and government structures?

**Comment by jGaboardi** [comment]
@sjsrey , @slumnitz and I decided to swap you out for @knaaptime on the Code of Conduct committee to spread out the "workload".

**Comment by jGaboardi** [comment]
@sjsrey Is there anything else I should for this or will you take care of the website merge/website refactoring?

**Comment by slumnitz** [comment]
> I decided to swap you out for @knaaptime on the Code of Conduct committee to spread out the "workload".

@sjsrey would you still like to be in the e-mail list? I could silence e-mails to web participation only for you. This way we have a backup committee member and you are not directly involved straight away if there is an issue?

**Pull request closed without merging**
